### PR TITLE
6 add card list item

### PR DESCRIPTION
**Pull request by OsosKP**
Removed all Detox dependencies and updated and reorganized troubleshooting documentation (README.md, TROUBLESHOOTING.md, SETUP_WINDOWS.md).

### CODE REVIEW

**Comment by chico** [comment]
It'd be great if App/Components/ListItems/CardListItem.js could be fixed up a touch:
 - Fix UI to better resemble what's in Figma
 - Add video support
 - Resolve todos
 - Remove unused properties

**Comment by ridgeontheway** [comment]
Will do :) just pushed to the branch to keep @OsosKP updated with my progress.

**Comment by chico** [comment]
@OsosKP @ridgeontheway lmk when you guys would like me to review this again 👍

**Comment by chico** [comment]
@OsosKP @ridgeontheway here's a list of stuff for us to chat about:
- Long imports should be broken into multiple lines for better readibility
- The componentDidMount method should remain inside its component
- Calls to setState should remain inside its component
- FYI The _isMounted variable isn't usually needed but neeed if there is any await calls inside componentDidMount, best if it remains inside its component for now
- getImageSize method should be refactored inside a ImageUtils service, i.e. not a module
- TouchableOpacity with Video elements and onVideoEnd, onVideoError, onVideoToggle methods should be refactored into a Video component, i.e. not a module
- Is UI still WIP? See attached screenshot

Screen Shot 2019-07-04 at 12 48 41

**Pull request merged**
